name: Build for macOS
on:
  push:
    branches:
      - github-action-test
  pull_request:
    branches:
      - github-action-test

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install N2
        run: |
          bash tools/install-n2

      - name: Install Git and rsync
        run: |
          brew install git rsync

      - name: Install audio tools
        run: |
          brew install mpv lame

      - name: Build
        run: |
          ./run

      - name: Bundle into dmg
        run: |
          git submodule update --checkout qt/bundle/PyOxidizer
          ./ninja bundle