name: Build for Windows

on:
  push:
    branches:
      - test-non-camera-permission
#  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add MSVC build tools
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install N2
        shell: bash
        run: |
          bash tools/install-n2

      - name: Install required packages (mpv, lame, etc.)
        shell: bash
        run: |
          choco install mpv lame -y

      - name: Update Git submodules
        shell: bash
        run: |
          git submodule update --checkout qt/bundle/PyOxidizer

      - name: Build Anki (with retries)
        shell: bash
        run: |
          max_tries=10
          i=0
          until ./ninja bundle
          do
              if [ $i -eq $max_tries ]
              then
                  echo 'Error: ./ninja bundle did not succeed even after 10 tries.'
                  exit 1
              fi
              echo "Retrying... ($i/$max_tries)"
              sleep 10
              i=$((i+1))
          done

      - name: List files in out directory
        shell: bash
        run: |
          ls -lhR out/bundle/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: anki-build-artifacts
          path: out/bundle/*
